# Linear Regression with cuML

## Python Simple Linear Regression Code.
``Limited to one feature``

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

In [2]:
df = pd.read_csv("data/advertising.csv")
df.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [3]:
df["total_spend"] = df.TV + df.Radio + df.Newspaper
df.head()

      TV  Radio  Newspaper  Sales  total_spend
0  230.1   37.8       69.2   22.1        337.1
1   44.5   39.3       45.1   10.4        128.9
2   17.2   45.9       69.3   12.0        132.4
3  151.5   41.3       58.5   16.5        251.3
4  180.8   10.8       58.4   17.9        250.0

In [12]:
fig = px.scatter(df, x="total_spend", y="Sales",
                hover_data=["Sales"],
                trendline="ols",
                title="Advertising Data",
                labels={
                    "Sales": "Sales (%)",
                    "total_spend": "Total Amount Spend ($)"
                })


fig.update_layout(xaxis_range=[0, max(df.total_spend) + 10],
                  yaxis_range=[1, max(df.Sales) + 3],
                 title_x=0.5,
                 font=dict(size=18))
fig.data[1].update(line_color="red")
fig.show()

In [16]:
np.polyfit(df.total_spend, df.Sales, deg=1)
# b1x + b0

array([0.0525585, 4.573573 ])

In [21]:
# b3x ** 3 + b2 ** 2 + b1x ** b0
w = np.polyfit(df.total_spend, df.Sales, deg=3)
w

array([ 4.49497819e-08, -7.06143726e-05,  7.48845278e-02,  2.94654345e+00])

In [22]:
sample_x = df.total_spend[0]
sample_y = df.Sales[0]
sample_x, sample_y

(337.09999999999997, 22.1)

In [32]:
sample_yh = sum(w[:-1] * sample_x) + w[-1]
sample_yh, sample_y # error is huge xD ML

(28.16632882485256, 22.1)