In [57]:
!pip install datasets transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: datasets in /usr/local/lib/python3.7/dist-packages (2.4.0)
Requirement already satisfied: transformers in /usr/local/lib/python3.7/dist-packages (4.22.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from datasets) (1.3.5)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from datasets) (4.12.0)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.7/dist-packages (from datasets) (4.64.1)
Requirement already satisfied: fsspec[http]>=2021.11.1 in /usr/local/lib/python3.7/dist-packages (from datasets) (2022.8.2)
Requirement already satisfied: dill<0.3.6 in /usr/local/lib/python3.7/dist-packages (from datasets) (0.3.5.1)
Requirement already satisfied: huggingface-hub<1.0.0,>=0.1.0 in /usr/local/lib/python3.7/dist-packages (from datasets) (0.9.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.7/dist-packages (from datasets) (3.0.0)
Requirement already satisfied: responses<0.19 in /usr/local/lib/python3.7/dist-packages (from datasets) (0.18.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from datasets) (21.3)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.7/dist-packages (from datasets) (3.8.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.7/dist-packages (from datasets) (1.21.6)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.7/dist-packages (from datasets) (2.23.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.7/dist-packages (from datasets) (0.70.13)
Requirement already satisfied: pyarrow>=6.0.0 in /usr/local/lib/python3.7/dist-packages (from datasets) (6.0.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets) (1.2.0)
Requirement already satisfied: asynctest==0.13.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets) (0.13.0)
Requirement already satisfied: typing-extensions>=3.7.4 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets) (4.1.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets) (6.0.2)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets) (2.1.1)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets) (4.0.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets) (1.8.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets) (22.1.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.7/dist-packages (from huggingface-hub<1.0.0,>=0.1.0->datasets) (3.8.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.7/dist-packages (from huggingface-hub<1.0.0,>=0.1.0->datasets) (6.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->datasets) (3.0.9)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->datasets) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->datasets) (2022.6.15)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->datasets) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->datasets) (1.25.11)
Requirement already satisfied: tokenizers!=0.11.3,<0.13,>=0.11.1 in /usr/local/lib/python3.7/dist-packages (from transformers) (0.12.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.7/dist-packages (from transformers) (2022.6.2)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->datasets) (3.8.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->datasets) (2022.2.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->datasets) (1.15.0)

# The Hugging Face Datasets Library

there were three main steps when it came to fine-tuning a model:

1. Load a dataset from the Hugging Face Hub.
2. Preprocess the data with Dataset.map().
3. Load and compute metrics.

But this is just scratching the surface of what 🤗 Datasets can do! In this notebook, we will take a deep dive into the library. Along the way, we’ll find answers to the following questions:

* What do you do when your dataset is not on the Hub?
* How can you slice and dice a dataset? (And what if you really need to use Pandas?)
* What do you do when your dataset is huge and will melt your laptop’s RAM?
* What the heck are “memory mapping” and Apache Arrow?
* How can you create your own dataset and push it to the Hub?

The techniques you learn here will prepare you for the advanced tokenization and fine-tuning tasks

##  What if my dataset isn't on the Hub?

We know how to use the Hugging Face Hub to download datasets, but you’ll often find yourself working with data that is stored either on your laptop or on a remote server. In this section we’ll show you how 🤗 Datasets can be used to load datasets that aren’t available on the Hugging Face Hub.

###  Working with local and remote datasets

🤗 Datasets provides loading scripts to handle the loading of local and remote datasets. It supports several common data formats, such as:
CSV & TSV, Text files, JSON & JSON Lines, Pickled DataFrames.

For each data format we just need to specify the type of loading script in the load_dataset() function, along with a data_files argument that specifies the path to one or more files. Let’s start by loading a dataset from local files; later we’ll see how to do the same with remote files.

### Loading a local dataset

For this example we’ll use the SQuAD-it dataset, which is a large-scale dataset for question answering in Italian.

The training and test splits are hosted on GitHub, so we can download them with a simple wget command:

In [1]:
!wget https://github.com/crux82/squad-it/raw/master/SQuAD_it-train.json.gz
!wget https://github.com/crux82/squad-it/raw/master/SQuAD_it-test.json.gz

--2022-09-18 11:50:21--  https://github.com/crux82/squad-it/raw/master/SQuAD_it-train.json.gz
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/crux82/squad-it/master/SQuAD_it-train.json.gz [following]
--2022-09-18 11:50:21--  https://raw.githubusercontent.com/crux82/squad-it/master/SQuAD_it-train.json.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7725286 (7.4M) [application/octet-stream]
Saving to: ‘SQuAD_it-train.json.gz’

SQuAD_it-train.json 100%[===================>]   7.37M  --.-KB/s    in 0.03s

2022-09-18 11:50:21 (273 MB/s) - ‘SQuAD_it-train.json.gz’ saved [7725286/7725286]

--2022-09-18 11:50:21--  https://github.com/crux82/squad-it/raw/master/SQuAD_it-test.json.gz
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/crux82/squad-it/master/SQuAD_it-test.json.gz [following]
--2022-09-18 11:50:21--  https://raw.githubusercontent.com/crux82/squad-it/master/SQuAD_it-test.json.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1051245 (1.0M) [application/octet-stream]
Saving to: ‘SQuAD_it-test.json.gz’

SQuAD_it-test.json. 100%[===================>]   1.00M  --.-KB/s    in 0.008s

2022-09-18 11:50:21 (121 MB/s) - ‘SQuAD_it-test.json.gz’ saved [1051245/1051245]

To load a JSON file with the load_dataset() function, we just need to know if we’re dealing with ordinary JSON (similar to a nested dictionary) or JSON Lines (line-separated JSON). Like many question answering datasets, SQuAD-it uses the nested format, with all the text stored in a data field. This means we can load the dataset by specifying the field argument as follows:

In [6]:
from datasets import load_dataset

squad_data = load_dataset("json", data_files={"train": "SQuAD_it-train.json.gz",
                                           "test": "SQuAD_it-test.json.gz"},
                       field="data")

WARNING:datasets.builder:Using custom data configuration default-e40aea9f5e1655ea

Downloading and preparing dataset json/default to /root/.cache/huggingface/datasets/json/default-e40aea9f5e1655ea/0.0.0/a3e658c4731e59120d44081ac10bf85dc7e1388126b92338344ce9661907f253...

Downloading data files:   0%|          | 0/2 [00:00<?, ?it/s]

Extracting data files:   0%|          | 0/2 [00:00<?, ?it/s]

0 tables [00:00, ? tables/s]

0 tables [00:00, ? tables/s]

Dataset json downloaded and prepared to /root/.cache/huggingface/datasets/json/default-e40aea9f5e1655ea/0.0.0/a3e658c4731e59120d44081ac10bf85dc7e1388126b92338344ce9661907f253. Subsequent calls will reuse this data.

  0%|          | 0/2 [00:00<?, ?it/s]

In [7]:
squad_data

DatasetDict({
    train: Dataset({
        features: ['title', 'paragraphs'],
        num_rows: 442
    })
    test: Dataset({
        features: ['title', 'paragraphs'],
        num_rows: 48
    })
})

This shows us the number of rows and the column names associated with the training set. We can view one of the examples by indexing into the train split as follows:

In [13]:
squad_data["train"][2]

{'title': '51º stato',
 'paragraphs': [{'context': 'La frase "51° stato" può essere usata in senso positivo, nel senso che una regione o territorio è così allineata, solidale e favorevole agli Stati Uniti che è come uno stato americano. Può anche essere utilizzato in senso peggiorativo, il che significa che un\' area o una regione è percepita come sottoposta a un\' eccessiva influenza o controllo militare o culturale americano. In vari paesi del mondo, le persone che credono che la loro cultura locale o nazionale sia troppo americanizzata usano talvolta il termine "51° stato" in riferimento al proprio paese. eccessiva influenza o controllo culturale o militare americano eccessivo.',
   'qas': [{'answers': [{'answer_start': 71,
       'text': 'una regione o territorio è così allineata, solidale e favorevole agli Stati Uniti'}],
     'id': '572eedffc246551400ce47bc',
     'question': 'Qual è la connotazione positiva dell\' etichetta "51° stato"?'}]},
  {'context': 'L\'articolo 4, III sezione della Costituzione degli Stati Uniti prevede il potere del Congresso di annettere nuovi stati all\'Unione. Per entrare nell\'Unione uno stato deve dare «"full faith and credit"» ("piena fiducia e credito") agli atti di tutte le assemblee legislative e di tutti i tribunali, compresi i contratti legali, i matrimoni e le sentenze penali. Di contro uno Stato annesso all\'Unione godrebbe della protezione militare e civile del Governo federale, che è anche tenuto a garantire una forma di governo repubblicana ad ogni Stato dell\'Unione.',
   'qas': []},
  {'context': "Puerto Rico è stato discusso come potenziale 51° stato degli Stati Uniti. In un referendum sullo status del 2012 la maggioranza degli elettori, il 54%, ha espresso insoddisfazione per l' attuale relazione politica. In una domanda separata, il 61 per cento degli elettori ha sostenuto la statualità (escludendo il 26 per cento degli elettori che hanno lasciato in bianco l' interrogazione). L' 11 dicembre 2012, il legislatore di Porto Rico ha deciso di chiedere che il Presidente e il Congresso degli Stati Uniti agiscano sui risultati, mettano fine all' attuale forma di status territoriale e avviino il processo di ammissione di Porto Rico all' Unione come stato. Puerto Rico è stato discusso come potenziale 51° stato degli Stati Uniti.",
   'qas': [{'answers': [{'answer_start': 147, 'text': '54%'}],
     'id': '572ef128c246551400ce47d5',
     'question': 'Quale percentuale di elettori ha sostenuto la statualità?'},
    {'answers': [{'answer_start': 393, 'text': '11 dicembre 2012'}],
     'id': '572ef128c246551400ce47d6',
     'question': 'Quando ha deciso Porto Rico di chiedere agli Stati Uniti di agire su questi risultati?'},
    {'answers': [{'answer_start': 429, 'text': 'Porto Rico'}],
     'id': '572ef128c246551400ce47d8',
     'question': 'Quale territorio è stato proposto come nuova aggiunta agli Stati Uniti?'},
    {'answers': [{'answer_start': 147, 'text': '54%'}],
     'id': '572efe86cb0c0d14000f16de',
     'question': "Quali percentuali di elettori hanno espresso infelicità per l' attuale rapporto politico tra Stati Uniti e Porto Rico?"},
    {'answers': [{'answer_start': 393, 'text': '11 dicembre 2012'}],
     'id': '572efe86cb0c0d14000f16df',
     'question': 'Quando ha chiesto al legislatore di Puerto Rico di essere considerato Stato?'}]},
  {'context': "Dal 1898, Puerto Rico ha una rappresentanza limitata al Congresso sotto forma di Commissario Residente, un delegato senza diritto di voto. Il 110° Congresso ha restituito al Commissario il potere di votare in seno al Comitato dell' intero, ma non su questioni in cui il voto rappresenterebbe una partecipazione decisiva. Puerto Rico ha le elezioni presidenziali degli Stati Uniti presidenziali primari o caucus del Partito Democratico e il Partito Repubblicano di selezionare i delegati alle rispettive convenzioni nazionali dei partiti, anche se gli elettori presidenziali non sono concessi sul collegio elettorale. Come cittadini americani, i portoricani possono votare alle elezioni presidenziali negli Stati Uniti, a condizione che risiedano in uno dei 50 stati o nel Distretto di Columbia e non nello stesso Porto Rico. Dal 1898.",
   'qas': [{'answers': [{'answer_start': 142, 'text': '110° Congresso'}],
     'id': '572eff62dfa6aa1500f8d540',
     'question': 'Quale Congresso ha dato al commissario il potere di votare?'}]},
  {'context': "I residenti di Puerto Rico pagano imposte federali statunitensi: tasse di import/export, tasse federali sulle materie prime, imposte sociali, contribuendo così al governo americano. La maggior parte dei residenti di Puerto Rico non pagano l' imposta federale sul reddito, ma pagano le imposte federali sui salari (Social Security e Medicare). Tuttavia, i dipendenti federali, quelli che fanno affari con il governo federale, Puerto Rico società con sede a Rico che intendono inviare fondi per gli Stati Uniti e altri fanno pagare le imposte federali sul reddito. Puerto Ricans può arruolarsi nei militari statunitensi. I portoricani hanno partecipato a tutte le guerre americane dal 1898;52 portoricani erano stati uccisi nella guerra in Iraq e in Afghanistan nel novembre 2012. Imposte federali statunitensi. Quali tipi di tasse pagano i portoricani? tasse di importazione/esportazione, tasse federali sulle materie prime, imposte sociali. Che cosa costituisce le tasse federali Puerto Rican cittadini ricani pagare? Puerto Ricans può arruolarsi nel militare degli Stati Uniti.",
   'qas': []},
  {'context': "Puerto Rico è stato sotto la sovranità degli Stati Uniti per oltre un secolo quando è stato ceduto agli Stati Uniti dalla Spagna dopo la fine della guerra ispano-americana, e Puerto Ricans sono stati cittadini statunitensi dal 1917. Lo status definitivo dell' isola non è stato determinato a partire dal 2012[aggiornamento], i suoi residenti non hanno la rappresentanza di voto nel loro governo federale. Puerto Rico ha una rappresentanza limitata al Congresso degli Stati Uniti sotto forma di Commissario Residente, un delegato senza diritto di voto limitato. Come gli stati, Puerto Rico ha l' autogoverno, una forma repubblicana di governo organizzata secondo una costituzione adottata dal suo popolo, e una polizza di diritti. Guerra Spagnolo-Americana. All' indomani di quale guerra gli Stati Uniti hanno concesso Puerto Rico? Spagna. Quale paese ha consegnato Portorico agli Stati Uniti? dal 1917. Da quanto tempo i portoricani sono cittadini statunitensi? repubblicano.",
   'qas': []},
  {'context': "Nel novembre 2012, un referendum ha portato il 54 per cento degli intervistati a votare per rifiutare lo status attuale ai sensi della clausola territoriale della Costituzione degli Stati Uniti, mentre una seconda domanda ha portato al 61 per cento degli elettori identificando la statualità come l' alternativa preferita allo status territoriale attuale. Il referendum del 2012 è stato di gran lunga il referendum di maggior successo per i sostenitori della statualità e il sostegno allo Stato è aumentato in ogni referendum popolare successivo. Tuttavia, più di un elettore su quattro si è astenuto dal rispondere alla domanda sullo status alternativo preferito. Gli oppositori dello Stato hanno sostenuto che l' opzione della statualità ha raccolto solo il 45 per cento dei voti se sono incluse le astensioni. Se si considerano le astensioni, il risultato del referendum è molto più vicino al 44 per cento per la statualità, un numero che cade sotto la soglia della maggioranza del 50 per cento. 54 per cento.",
   'qas': [{'answers': [{'answer_start': 564,
       'text': 'un elettore su quattro'}],
     'id': '5730429d04bcaa1900d77438',
     'question': 'Quale percentuale degli elettori si è astenuta dal voto su uno status alternativo preferito?'}]},
  {'context': 'Il Washington Post, il New York Times e il Boston Herald hanno pubblicato pareri che esprimono il loro sostegno alla statualità di Porto Rico. L\' 8 novembre 2012, Washington, il quotidiano The Hill ha pubblicato un articolo in cui si afferma che il Congresso probabilmente ignorerà i risultati del referendum a causa delle circostanze che stanno alla base dei voti. e Stati Uniti d\' America Il membro del Congresso Luis Gutiérrez U. S. U. Nydia Velázquez, entrambi di origini portoricane, si è dichiarato d\' accordo con le dichiarazioni di The Hill. Poco dopo la pubblicazione dei risultati, Puerto Rico-nato negli Stati Uniti. Il membro del Congresso José Enrique Serrano ha commentato:"Sono rimasto particolarmente colpito dall\' esito del referendum sullo" status "tenutosi a Porto Rico. La maggioranza dei votanti ha segnalato la volontà di modificare l\' attuale assetto territoriale. In una seconda domanda, una maggioranza ancora più ampia ha chiesto di diventare Stato. Questo è un terremoto nella politica di Puerto Rican. Richiederà l\' attenzione del Congresso, e una risposta definitiva alla richiesta di cambiamento del Porto Rican. Questo è un momento storico in cui gli elettori hanno chiesto di andare avanti".',
   'qas': [{'answers': [{'answer_start': 189, 'text': 'The Hill'}],
     'id': '57304372a23a5019007fd020',
     'question': 'Che cosa ha suggerito che il Congresso avrebbe ignorato il referendum di Puerto Rico?'},
    {'answers': [{'answer_start': 0,
       'text': 'Il Washington Post, il New York Times e il Boston Herald'}],
     'id': '57304372a23a5019007fd01f',
     'question': 'Quali giornali hanno pubblicato articoli di opinione che esprimono il loro sostegno alla statualità di Puerto Rico?'},
    {'answers': [{'answer_start': 146, 'text': '8 novembre 2012'}],
     'id': '57304372a23a5019007fd021',
     'question': "Quando è stato pubblicato l' articolo?"}]},
  {'context': 'Alcuni giorni dopo il referendum, il Commissario Pedro Pierluisi, Governatore Luis Fortuño, e il Governatore eletto Alejandro García Padilla hanno scritto al Presidente degli Stati Uniti Barack Obama lettere separate sui risultati delle votazioni. Pierluisi ha esortato Obama ad iniziare la legislazione a favore della statualità di Puerto Rico, alla luce della sua vittoria nel referendum. Fortuño lo esortò a portare avanti il processo. García Padilla gli chiese di respingere i risultati a causa della loro ambiguità. La posizione della Casa Bianca relativa al plebiscito del novembre 2012 era che i risultati erano chiari, il popolo di Puerto Rico vuole la questione dello status risolto, e una maggioranza ha scelto lo stato nella seconda domanda. L\' ex direttore della Casa Bianca dei media ispanici ha dichiarato:"Ora è ora che il Congresso agisca e l\' amministrazione lavorerà con loro su questo sforzo, in modo che il popolo di Puerto Rico possa determinare il proprio futuro".',
   'qas': [{'answers': [{'answer_start': 37,
       'text': 'Commissario Pedro Pierluisi, Governatore Luis Fortuño'}],
     'id': '573044ce947a6a140053d386',
     'question': 'Quali politici hanno spinto per la statualità di Puerto Rico?'},
    {'answers': [{'answer_start': 97,
       'text': 'Governatore eletto Alejandro García Padilla'}],
     'id': '573044ce947a6a140053d387',
     'question': 'Quale politico ha combattuto contro la statualità per Puerto Rico?'}]},
  {'context': 'Il 15 maggio 2013, il Commissario Pierluisi ha presentato H. R. 2000 al Congresso per "definire il processo per l\' ammissione di Porto Rico come stato dell\' Unione", chiedendo al Congresso di votare sulla ratifica di Porto Rico come 51° stato. Il 12 febbraio 2014, il senatore Martin Heinrich ha presentato un disegno di legge al Senato degli Stati Uniti. Il progetto di legge richiederebbe l\' indizione di un referendum vincolante a Portorico per chiedere se il territorio vuole essere ammesso come Stato.',
   'qas': []},
  {'context': 'Washington, DC è spesso citato come candidato alla statualità. In Federalista No. 43 di The Federalist Papers, James Madison ha considerato le implicazioni della definizione di "sede del governo" contenuta nella Costituzione degli Stati Uniti. Anche se ha notato potenziali conflitti di interesse, e la necessità di una "legislatura comunale per scopi locali", Madison non ha affrontato il ruolo del distretto nel voto nazionale. Gli studiosi di diritto non sono d\' accordo sul fatto che un semplice atto del Congresso possa ammettere il Distretto come Stato, a causa del suo status di sede del governo degli Stati Uniti, che l\' Articolo I, Sezione 8 della Costituzione richiede di essere sotto la giurisdizione esclusiva del Congresso; a seconda dell\' interpretazione di questo testo, l\' ammissione del Distretto intero come Stato può richiedere un emendamento costituzionale, che è molto più difficile da mettere in pratica. Tuttavia, la Costituzione non stabilisce una dimensione minima per il Distretto. Le sue dimensioni sono già cambiate una volta, quando Virginia ha recuperato la porzione del Distretto a sud del Potomac. Così il requisito costituzionale per un distretto federale può essere soddisfatto riducendo le sue dimensioni al piccolo nucleo centrale di edifici governativi e monumenti, dando il resto del territorio al nuovo Stato. Giacomo Madison.',
   'qas': [{'answers': [{'answer_start': 111, 'text': 'James Madison'}],
     'id': '573047ca947a6a140053d396',
     'question': 'Dove si trovano queste idee nei documenti federalisti?'}]},
  {'context': 'Washington, D. C. residenti che sostengono il movimento statualitÃ\xa0 a volte usano una versione abbreviata del motto di protesta della guerra rivoluzionaria "nessuna tassazione senza rappresentanza", omettendo l\' iniziale "No", denotando la loro mancanza di rappresentanza congressuale, la frase Ã¨ ora stampata su recentemente pubblicato Washington, D. C. targhe (anche se un driver puÃ² scegliere di avere l\' indirizzo del sito web Washington, DC invece). La limousine presidenziale del presidente Bill Clinton aveva la targa "Taxation without representation" in ritardo nel suo mandato, mentre il presidente George W. Bush aveva cambiato le targhe del veicolo poco dopo l\' inizio del suo mandato.',
   'qas': [{'answers': [{'answer_start': 237,
       'text': 'la loro mancanza di rappresentanza congressuale'}],
     'id': '57304a372461fd1900a9ccf4',
     'question': 'Che cosa è la frase di protesta?'}]},
  {'context': "Questa posizione è stata assunta dal D. C. Statehood Party, un partito politico; da allora si è fusa con l' affiliata locale del partito verde per formare il D. C. Statehood Green Party. Il movimento più vicino a questo movimento è mai venuto al successo è stato nel 1978, quando il Congresso ha approvato il Distretto di Columbia voto Diritto di voto Emendamento. Due anni dopo, nel 1980, i cittadini locali approvarono un' iniziativa che chiedeva una convenzione costituzionale per un nuovo Stato. Nel 1982, gli elettori ratificarono la costituzione dello Stato, che doveva essere chiamato Nuova Columbia.",
   'qas': [{'answers': [{'answer_start': 267, 'text': '1978'}],
     'id': '57304ae58ab72b1400f9c3f6',
     'question': 'Quando il movimento si è avvicinato di più al successo?'},
    {'answers': [{'answer_start': 592, 'text': 'Nuova Columbia'}],
     'id': '57304ae58ab72b1400f9c3f7',
     'question': 'Quale sarebbe il nuovo nome dello Stato DC?'}]},
  {'context': 'Altri contendenti meno probabili sono Guam e le Isole Vergini degli Stati Uniti, entrambe non costituite in società, territori organizzati degli Stati Uniti. Inoltre, le isole Marianne settentrionali e Samoa americane, un territorio non sindacalizzato e senza personalità giuridica, potrebbero entrambi cercare di ottenere la sovranità. Alcune proposte prevedono l\' ammissione delle Isole Vergini con Porto Rico come Stato unico (spesso conosciuto come il proposto "Commonwealth di Prusvi", per Porto Rico/USA). Isole Vergini, o come "Puerto Virgo"), e per l\' amalgama dei territori degli Stati Uniti o ex territori nell\' Oceano Pacifico, nel modo del concetto di "Greater Hawaii" degli anni Sessanta. Guam e le Isole Marianne del Nord sarebbero ammesse come un unico Stato, insieme a Palau, agli Stati Federati di Micronesia e alle Isole Marshall (anche se queste ultime tre entità sono ora nazioni sovrane separate, che hanno un patto di libero accordo di associazione con gli Stati Uniti). Tale stato avrebbe una popolazione di 412.381 abitanti (leggermente inferiore alla popolazione del Wyoming) e una superficie di 911,82 miglia quadrate (2.361,6 km2) (leggermente più piccola dell\' isola di Rodi). Samoa americana potrebbe forse essere parte di tale stato, aumentando la popolazione a 467.900 e l\' area a 988,65 miglia quadrate (2.560,6 km2). Radio Australia, alla fine di maggio 2008, ha lanciato segnali di Guam e delle Isole Marianne del Nord, tornando a diventare il 51° Stato. Guam.',
   'qas': [{'answers': [{'answer_start': 38, 'text': 'Guam'}],
     'id': '573071c5069b5314008320d7',
     'question': 'Qual è un altro paese probabile per la statualità?'},
    {'answers': [{'answer_start': 1350, 'text': 'Radio Australia'}],
     'id': '573071c5069b5314008320d8',
     'question': 'Quale entità ha riferito che Guam e le Isole Marianne del Nord sono tornate a farlo?'}]},
  {'context': 'Le Filippine hanno avuto piccoli movimenti di base per la statualità degli Stati Uniti. Originariamente parte della piattaforma del Partito Progressivo, allora conosciuto come Federalista Partito, il partito caduto nel 1907, che ha coinciso con il cambiamento di nome. Non più tardi del 2004, il concetto che le Filippine diventino uno Stato statunitense è stato parte di una piattaforma politica nelle Filippine. I sostenitori di questo movimento includono i filippini che credono che la qualità della vita nelle Filippine sarebbe più alta e che ci sarebbe meno povertà se le Filippine fossero uno stato o un territorio americano. I sostenitori includono anche i filippini che avevano combattuto come membri delle forze armate degli Stati Uniti in varie guerre durante il periodo del Commonwealth. Filippine. Quale paese aveva un piccolo movimento di base per lo Stato americano? Federalista Partito.',
   'qas': []},
  {'context': 'In Canada,"il 51esimo stato" è una frase generalmente usata in modo tale da implicare che se si prende un certo corso politico, il destino del Canada sarà poco più di una parte degli Stati Uniti. Tra gli esempi si possono citare l\' accordo di libero scambio Canada-Stati Uniti del 1988, il dibattito sulla creazione di un perimetro di difesa comune, e come potenziale conseguenza della mancata adozione di proposte volte a risolvere la questione della sovranità del Quebec, l\' accordo di Charlottetown del 1992 e la legge sulla chiarezza del 1999.',
   'qas': [{'answers': [{'answer_start': 281, 'text': '1988'}],
     'id': '57307298396df9190009610b',
     'question': "Quando è stato approvato l' accordo di libero scambio Canada-US?"},
    {'answers': [{'answer_start': 506, 'text': '1992'}],
     'id': '57307298396df9190009610c',
     'question': "Quando è stato firmato l' Accordo di Charlottetown?"},
    {'answers': [{'answer_start': 542, 'text': '1999'}],
     'id': '57307298396df9190009610d',
     'question': 'Quando è entrata in vigore la legge sulla chiarezza?'}]},

This can be useful if you don’t want to manually decompress many GZIP files. The automatic decompression also applies to other common formats like ZIP and TAR, so you just need to point data_files to the compressed files and you’re good to go!

###  Loading a remote dataset

If you’re working as a data scientist or coder in a company, there’s a good chance the datasets you want to analyze are stored on some remote server. Fortunately, loading remote files is just as simple as loading local ones! Instead of providing a path to local files, we point the data_files argument of load_dataset() to one or more URLs where the remote files are stored. For example, for the SQuAD-it dataset hosted on GitHub, we can just point data_files to the SQuAD_it-*.json.gz URLs as follows:

In [14]:
url = "https://github.com/crux82/squad-it/raw/master/"
data_files = {
    "train": url + "SQuAD_it-train.json.gz",
    "test": url + "SQuAD_it-test.json.gz",
}
squad_dataset = load_dataset("json", data_files=data_files, field="data")
squad_dataset

WARNING:datasets.builder:Using custom data configuration default-b2375dfabd7ba663

Downloading and preparing dataset json/default to /root/.cache/huggingface/datasets/json/default-b2375dfabd7ba663/0.0.0/a3e658c4731e59120d44081ac10bf85dc7e1388126b92338344ce9661907f253...

Downloading data files:   0%|          | 0/2 [00:00<?, ?it/s]

Downloading data:   0%|          | 0.00/7.73M [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/1.05M [00:00<?, ?B/s]

Extracting data files:   0%|          | 0/2 [00:00<?, ?it/s]

0 tables [00:00, ? tables/s]

0 tables [00:00, ? tables/s]

Dataset json downloaded and prepared to /root/.cache/huggingface/datasets/json/default-b2375dfabd7ba663/0.0.0/a3e658c4731e59120d44081ac10bf85dc7e1388126b92338344ce9661907f253. Subsequent calls will reuse this data.

  0%|          | 0/2 [00:00<?, ?it/s]

DatasetDict({
    train: Dataset({
        features: ['title', 'paragraphs'],
        num_rows: 442
    })
    test: Dataset({
        features: ['title', 'paragraphs'],
        num_rows: 48
    })
})

This returns the same DatasetDict object obtained above, but saves us the step of manually downloading and decompressing the SQuAD_it-*.json.gz files. This wraps up our foray into the various ways to load datasets that aren’t hosted on the Hugging Face Hub.

##  Time to slice and dice

Most of the time, the data you work with won’t be perfectly prepared for training models. In this section we’ll explore the various features that 🤗 Datasets provides to clean up your datasets.

### Slicing and dicing our data

Similar to Pandas, 🤗 Datasets provides several functions to manipulate the contents of Dataset and DatasetDict objects. We already encountered the Dataset.map() and in this section we’ll explore some of the other functions at our disposal.

For this example we’ll use the Drug Review Dataset that’s hosted on the UC Irvine Machine Learning Repository, which contains patient reviews on various drugs, along with the condition being treated and a 10-star rating of the patient’s satisfaction.

First we need to download and extract the data, which can be done with the wget and unzip commands:

In [15]:
!wget "https://archive.ics.uci.edu/ml/machine-learning-databases/00462/drugsCom_raw.zip"
!unzip drugsCom_raw.zip

--2022-09-18 12:13:33--  https://archive.ics.uci.edu/ml/machine-learning-databases/00462/drugsCom_raw.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 42989872 (41M) [application/x-httpd-php]
Saving to: ‘drugsCom_raw.zip’

drugsCom_raw.zip    100%[===================>]  41.00M  29.1MB/s    in 1.4s

2022-09-18 12:13:35 (29.1 MB/s) - ‘drugsCom_raw.zip’ saved [42989872/42989872]

Archive:  drugsCom_raw.zip
  inflating: drugsComTest_raw.tsv
  inflating: drugsComTrain_raw.tsv

Since TSV is just a variant of CSV that uses tabs instead of commas as the separator, we can load these files by using the csv loading script and specifying the delimiter argument in the load_dataset() function as follows:

In [16]:
from datasets import load_dataset

data_files = {"train": "drugsComTrain_raw.tsv", "test": "drugsComTest_raw.tsv"}

drug_dataset = load_dataset("csv", data_files=data_files,
                            delimiter="\t")
drug_dataset

WARNING:datasets.builder:Using custom data configuration default-3761173c276c0a9a

Downloading and preparing dataset csv/default to /root/.cache/huggingface/datasets/csv/default-3761173c276c0a9a/0.0.0/652c3096f041ee27b04d2232d41f10547a8fecda3e284a79a0ec4053c916ef7a...

Downloading data files:   0%|          | 0/2 [00:00<?, ?it/s]

Extracting data files:   0%|          | 0/2 [00:00<?, ?it/s]

0 tables [00:00, ? tables/s]

0 tables [00:00, ? tables/s]

Dataset csv downloaded and prepared to /root/.cache/huggingface/datasets/csv/default-3761173c276c0a9a/0.0.0/652c3096f041ee27b04d2232d41f10547a8fecda3e284a79a0ec4053c916ef7a. Subsequent calls will reuse this data.

  0%|          | 0/2 [00:00<?, ?it/s]

DatasetDict({
    train: Dataset({
        features: ['Unnamed: 0', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 161297
    })
    test: Dataset({
        features: ['Unnamed: 0', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 53766
    })
})

A good practice when doing any sort of data analysis is to grab a small random sample to get a quick feel for the type of data you’re working with. In 🤗 Datasets, we can create a random sample by chaining the Dataset.shuffle() and Dataset.select() functions together:

In [21]:
drug_sample = drug_dataset["train"].shuffle(42).select(range(1000))
drug_sample[:3]

{'Unnamed: 0': [87571, 178045, 80482],
 'drugName': ['Naproxen', 'Duloxetine', 'Mobic'],
 'condition': ['Gout, Acute', 'ibromyalgia', 'Inflammatory Conditions'],
 'review': ['"like the previous person mention, I&#039;m a strong believer of aleve, it works faster for my gout than the prescription meds I take. No more going to the doctor for refills.....Aleve works!"',
  '"I have taken Cymbalta for about a year and a half for fibromyalgia pain. It is great\r\nas a pain reducer and an anti-depressant, however, the side effects outweighed \r\nany benefit I got from it. I had trouble with restlessness, being tired constantly,\r\ndizziness, dry mouth, numbness and tingling in my feet, and horrible sweating. I am\r\nbeing weaned off of it now. Went from 60 mg to 30mg and now to 15 mg. I will be\r\noff completely in about a week. The fibro pain is coming back, but I would rather deal with it than the side effects."',
  '"I have been taking Mobic for over a year with no side effects other than an elevated blood pressure.  I had severe knee and ankle pain which completely went away after taking Mobic.  I attempted to stop the medication however pain returned after a few days."'],
 'rating': [9.0, 3.0, 10.0],
 'date': ['September 2, 2015', 'November 7, 2011', 'June 5, 2013'],
 'usefulCount': [36, 13, 128]}

Dataset.select() expects an iterable of indices, so we’ve passed range(1000) to grab the first 1,000 examples from the shuffled dataset. From this sample we can already see a few quirks in our dataset:

* The Unnamed: 0 column looks suspiciously like an anonymized ID for each patient.
* The condition column includes a mix of uppercase and lowercase labels.
* The reviews are of varying length and contain a mix of Python line separators (\r\n) as well as HTML character codes like &\#039;.

Let’s see how we can use 🤗 Datasets to deal with each of these issues. To test the patient ID hypothesis for the Unnamed: 0 column, we can use the Dataset.unique() function to verify that the number of IDs matches the number of rows in each split:

In [26]:
for split in drug_dataset.keys():
  assert len(drug_dataset[split]) == len(drug_dataset[split].unique("Unnamed: 0"))

This seems to confirm our hypothesis, so let’s clean up the dataset a bit by renaming the Unnamed: 0 column to something a bit more interpretable. We can use the DatasetDict.rename_column() function to rename the column across both splits in one go:

In [27]:
drug_dataset = drug_dataset.rename_column(
    original_column_name="Unnamed: 0",
    new_column_name="patient_id"
)
drug_dataset

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 161297
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 53766
    })
})

**``Try it out!``**

``Use the Dataset.unique() function to find the number of unique drugs and conditions in the training and test sets.``

In [29]:
for i in drug_dataset.keys():
    print(f"unique drugs in {i}: {len(drug_dataset[i].unique('drugName'))}")
    print(f"unique condition in {i}: {len(drug_dataset[i].unique('condition'))}")

unique drugs in train: 3436
unique condition in train: 885
unique drugs in test: 2637
unique condition in test: 709

Next, let’s normalize all the condition labels using Dataset.map().
we can define a simple function that can be applied across all the rows of each split in drug_dataset:

In [31]:
def lowercase_condition(x):
    return {"condition": x["condition"].lower()}

In [32]:
drug_dataset.map(lowercase_condition)

  0%|          | 0/161297 [00:00<?, ?ex/s]

AttributeError: ignored

We’ve run into a problem with our map function! From the error we can infer that some of the entries in the condition column are None, which cannot be lowercased as they’re not strings. Let’s drop these rows using Dataset.filter(), which works in a similar way to Dataset.map() and expects a function that receives a single example of the dataset. Instead of writing an explicit function like:

In [34]:
drug_dataset = drug_dataset.filter(lambda x: x["condition"] is not None)

  0%|          | 0/162 [00:00<?, ?ba/s]

  0%|          | 0/54 [00:00<?, ?ba/s]

In [36]:
drug_dataset = drug_dataset.map(lowercase_condition)
drug_dataset["train"]["condition"][:3]

WARNING:datasets.arrow_dataset:Loading cached processed dataset at /root/.cache/huggingface/datasets/csv/default-3761173c276c0a9a/0.0.0/652c3096f041ee27b04d2232d41f10547a8fecda3e284a79a0ec4053c916ef7a/cache-e58a5baec126caf0.arrow

  0%|          | 0/53471 [00:00<?, ?ex/s]

['left ventricular dysfunction', 'adhd', 'birth control']

It works! Now that we’ve cleaned up the labels, let’s take a look at cleaning up the reviews themselves.

### Creating new columns

Whenever you’re dealing with customer reviews, a good practice is to check the number of words in each review. A review might be just a single word like “Great!” or a full-blown essay with thousands of words, and depending on the use case you’ll need to handle these extremes differently. To compute the number of words in each review, we’ll use a rough heuristic based on splitting each text by whitespace.

Let’s define a simple function that counts the number of words in each review:

In [39]:
def compute_review_length(x):
    return {"review_length": len(x["review"].split())}

Unlike our lowercase_condition() function, compute_review_length() returns a dictionary whose key does not correspond to one of the column names in the dataset. In this case, when compute_review_length() is passed to Dataset.map(), it will be applied to all the rows in the dataset to create a new review_length column:

In [40]:
drug_dataset = drug_dataset.map(compute_review_length)

  0%|          | 0/160398 [00:00<?, ?ex/s]

  0%|          | 0/53471 [00:00<?, ?ex/s]

In [41]:
drug_dataset["train"][0]

{'patient_id': 206461,
 'drugName': 'Valsartan',
 'condition': 'left ventricular dysfunction',
 'review': '"It has no side effect, I take it in combination of Bystolic 5 Mg and Fish Oil"',
 'rating': 9.0,
 'date': 'May 20, 2012',
 'usefulCount': 27,
 'review_length': 17}

As expected, we can see a review_length column has been added to our training set. We can sort this new column with Dataset.sort() to see what the extreme values look like:

In [42]:
drug_dataset["train"].sort("review_length")[:3]

{'patient_id': [103488, 23627, 20558],
 'drugName': ['Loestrin 21 1 / 20', 'Chlorzoxazone', 'Nucynta'],
 'condition': ['birth control', 'muscle spasm', 'pain'],
 'review': ['"Excellent."', '"useless"', '"ok"'],
 'rating': [10.0, 1.0, 6.0],
 'date': ['November 4, 2008', 'March 24, 2017', 'August 20, 2016'],
 'usefulCount': [5, 2, 10],
 'review_length': [1, 1, 1]}

In [44]:
drug_dataset["train"].sort("review_length", reverse=True)["review_length"][:3]

WARNING:datasets.arrow_dataset:Loading cached sorted indices for dataset at /root/.cache/huggingface/datasets/csv/default-3761173c276c0a9a/0.0.0/652c3096f041ee27b04d2232d41f10547a8fecda3e284a79a0ec4053c916ef7a/cache-c63104faa072cd25.arrow

[1894, 1162, 1107]

As we suspected, some reviews contain just a single word, which, although it may be okay for sentiment analysis, would not be informative if we want to predict the condition.




```
🙋 An alternative way to add new columns to a dataset is with the Dataset.add_column() 
function. This allows you to provide the column as a Python list or NumPy array and can be handy 
in situations where Dataset.map() is not well suited for your analysis.
```

Let’s use the Dataset.filter() function to remove reviews that contain fewer than 30 words and longer than 1024 words. Similarly to what we did with the condition column, we can filter out the very short reviews by requiring that the reviews have a length above this threshold:

In [45]:
drug_dataset = drug_dataset.filter(lambda x: (x["review_length"] > 30) and
                                   (x["review_length"] <= 1024))

drug_dataset

  0%|          | 0/161 [00:00<?, ?ba/s]

  0%|          | 0/54 [00:00<?, ?ba/s]

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 138509
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 46107
    })
})

As you can see, this has removed around 15% of the reviews from our original training and test sets.

The last thing we need to deal with is the presence of HTML character codes in our reviews. We can use Python’s html module to unescape these characters, like so:

In [47]:
import html

text = "I&#039;m a transformer called BERT"
html.unescape(text)

"I'm a transformer called BERT"

We’ll use Dataset.map() to unescape all the HTML characters in our corpus:

In [48]:
drug_dataset = drug_dataset.map(lambda x: {"review": html.unescape(x["review"])})

  0%|          | 0/138509 [00:00<?, ?ex/s]

  0%|          | 0/46107 [00:00<?, ?ex/s]

As you can see, the Dataset.map() method is quite useful for processing data — and we haven’t even scratched the surface of everything it can do!

### The map() method's superpowers

The Dataset.map() method takes a batched argument that, if set to True, causes it to send a batch of examples to the map function at once (the batch size is configurable but defaults to 1,000). For instance, the previous map function that unescaped all the HTML took a bit of time to run (you can read the time taken from the progress bars). We can speed this up by processing several elements at the same time using a list comprehension.


When you specify batched=True the function receives a dictionary with the fields of the dataset, but each value is now a list of values, and not just a single value. The return value of Dataset.map() should be the same: a dictionary with the fields we want to update or add to our dataset, and a list of values. For example, here is another way to unescape all HTML characters, but using batched=True:

In [49]:
new_drug_dataset = drug_dataset.map(
    lambda x: {"review": [html.unescape(i) for i in x["review"]]},
    batched=True
)

  0%|          | 0/139 [00:00<?, ?ba/s]

  0%|          | 0/47 [00:00<?, ?ba/s]

If you’re running this code in a notebook, you’ll see that this command executes way faster than the previous one. And it’s not because our reviews have already been HTML-unescaped — if you re-execute the instruction from the previous section (without batched=True), it will take the same amount of time as before. This is because list comprehensions are usually faster than executing the same code in a for loop, and we also gain some performance by accessing lots of elements at the same time instead of one by one.

Using Dataset.map() with batched=True will be essential to unlock the speed of the “fast” tokenizers that we’ll encounter in later, which can quickly tokenize big lists of texts. For instance, to tokenize all the drug reviews with a fast tokenizer, we could use a function like this:

In [51]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

def tokenize_function(x):
  return tokenizer(x["review"], truncation=True)

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.

Moving 0 files to the new cache system

0it [00:00, ?it/s]

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/213k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/436k [00:00<?, ?B/s]

we can pass one or several examples to the tokenizer, so we can use this function with or without batched=True. Let’s take this opportunity to compare the performance of the different options. In a notebook, you can time a one-line instruction by adding %time before the line of code you wish to measure:

**Without batched=True**

In [52]:
%time tokenized_dataset = drug_dataset.map(tokenize_function)

  0%|          | 0/138509 [00:00<?, ?ex/s]

  0%|          | 0/46107 [00:00<?, ?ex/s]

CPU times: user 2min 12s, sys: 1.69 s, total: 2min 14s
Wall time: 2min 20s

**With Batched=True**

In [53]:
%time tokenized_dataset = drug_dataset.map(tokenize_function, batched=True)

  0%|          | 0/139 [00:00<?, ?ba/s]

  0%|          | 0/47 [00:00<?, ?ba/s]

CPU times: user 1min 30s, sys: 1.04 s, total: 1min 31s
Wall time: 57.6 s

This means that using a fast tokenizer with the batched=True option is 30 times faster than its slow counterpart with no batching — this is truly amazing! That’s the main reason why fast tokenizers are the default when using AutoTokenizer (and why they are called “fast”). They’re able to achieve such a speedup because behind the scenes the tokenization code is executed in Rust, which is a language that makes it easy to parallelize code execution.

Parallelization is also the reason for the nearly 6x speedup the fast tokenizer achieves with batching: you can’t parallelize a single tokenization operation, but when you want to tokenize lots of texts at the same time you can just split the execution across several processes, each responsible for its own texts.

Dataset.map() also has some parallelization capabilities of its own. Since they are not backed by Rust, they won’t let a slow tokenizer catch up with a fast one, but they can still be helpful (especially if you’re using a tokenizer that doesn’t have a fast version). To enable multiprocessing, use the num_proc argument and specify the number of processes to use in your call to Dataset.map():

In [55]:
slow_tokenizer = AutoTokenizer.from_pretrained("bert-base-cased",
                                               use_fast=True)

def slow_tokenize_function(x):
    return slow_tokenizer(x["review"], truncation=True)

In [56]:
tokenized_dataset = drug_dataset.map(slow_tokenize_function, batched=True,
                                     num_proc=8)

#0:   0%|          | 0/18 [00:00<?, ?ba/s]

#1:   0%|          | 0/18 [00:00<?, ?ba/s]

#2:   0%|          | 0/18 [00:00<?, ?ba/s]

#3:   0%|          | 0/18 [00:00<?, ?ba/s]

#4:   0%|          | 0/18 [00:00<?, ?ba/s]

#5:   0%|          | 0/18 [00:00<?, ?ba/s]

#7:   0%|          | 0/18 [00:00<?, ?ba/s]

#6:   0%|          | 0/18 [00:00<?, ?ba/s]

#0:   0%|          | 0/6 [00:00<?, ?ba/s]

#1:   0%|          | 0/6 [00:00<?, ?ba/s]

#2:   0%|          | 0/6 [00:00<?, ?ba/s]

#3:   0%|          | 0/6 [00:00<?, ?ba/s]

#4:   0%|          | 0/6 [00:00<?, ?ba/s]

#5:   0%|          | 0/6 [00:00<?, ?ba/s]

#6:   0%|          | 0/6 [00:00<?, ?ba/s]

#7:   0%|          | 0/6 [00:00<?, ?ba/s]

Those are much more reasonable results for the slow tokenizer, but the performance of the fast tokenizer was also substantially improved. Note, however, that won’t always be the case — for values of num_proc other than 8, our tests showed that it was faster to use batched=True without that option. In general, we don’t recommend using Python multiprocessing for fast tokenizers with batched=True.



```
Using num_proc to speed up your processing is usually a great idea, as long as the function you 
are using is not already doing some kind of multiprocessing of its own.
```

All of this functionality condensed into a single method is already pretty amazing, but there’s more! With Dataset.map() and batched=True you can change the number of elements in your dataset. This is super useful in many situations where you want to create several training features from one example, and we will need to do this as part of the preprocessing for several of the NLP tasks 



```
💡 In machine learning, an example is usually defined as the set of features that we feed to 
the model. In some contexts, these features will be the set of columns in a Dataset, but in others 
(like here and for question answering), multiple features can be extracted from a single example 
and belong to a single column.
```

Let’s have a look at how it works! Here we will tokenize our examples and truncate them to a maximum length of 128, but we will ask the tokenizer to return all the chunks of the texts instead of just the first one. This can be done with return_overflowing_tokens=True:

In [58]:
def tokenize_and_split(x):
  return tokenizer(
      x["review"],
      truncation=True,
      max_length=128,
      return_overflowing_tokens=True
  )

Let’s test this on one example before using Dataset.map() on the whole dataset:

In [59]:
result = tokenize_and_split(drug_dataset["train"][0])
[len(i) for i in result["input_ids"]]

[128, 49]

So, our first example in the training set became two features because it was tokenized to more than the maximum number of tokens we specified: the first one of length 128 and the second one of length 49. Now let’s do this for all elements of the dataset!

In [64]:
tokenized_dataset = drug_dataset.map(tokenize_and_split, batched=True)

  0%|          | 0/139 [00:00<?, ?ba/s]

ArrowInvalid: ignored

That didn’t work! Why not? Looking at the error message will give us a clue: there is a mismatch in the lengths of one of the columns, one being of length 1,463 and the other of length 1,000. If you’ve looked at the Dataset.map() documentation, you may recall that it’s the number of samples passed to the function that we are mapping; here those 1,000 examples gave 1,463 new features, resulting in a shape error.


The problem is that we’re trying to mix two different datasets of different sizes: the drug_dataset columns will have a certain number of examples (the 1,000 in our error), but the tokenized_dataset we are building will have more (the 1,463 in the error message). That doesn’t work for a Dataset, so we need to either remove the columns from the old dataset or make them the same size as they are in the new dataset. We can do the former with the remove_columns argument:

In [65]:
tokenized_dataset = drug_dataset.map(
    tokenize_and_split, batched=True,
    remove_columns=drug_dataset["train"].column_names
)
tokenized_dataset

  0%|          | 0/139 [00:00<?, ?ba/s]

  0%|          | 0/47 [00:00<?, ?ba/s]

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'token_type_ids', 'attention_mask', 'overflow_to_sample_mapping'],
        num_rows: 206707
    })
    test: Dataset({
        features: ['input_ids', 'token_type_ids', 'attention_mask', 'overflow_to_sample_mapping'],
        num_rows: 68864
    })
})

Now this works without error. We can check that our new dataset has many more elements than the original dataset by comparing the lengths:

In [66]:
len(tokenized_dataset["train"]), len(drug_dataset["train"])

(206707, 138509)

We mentioned that we can also deal with the mismatched length problem by making the old columns the same size as the new ones. To do this, we will need the overflow_to_sample_mapping field the tokenizer returns when we set return_overflowing_tokens=True. It gives us a mapping from a new feature index to the index of the sample it originated from. Using this, we can associate each key present in our original dataset with a list of values of the right size by repeating the values of each example as many times as it generates new features:

In [68]:
def tokenize_and_split(x):
  result = tokenizer(
      x["review"],
      truncation=True,
      max_length=128,
      return_overflowing_tokens=True
  )
  sample_map = result.pop("overflow_to_sample_mapping")
  for key, val in x.items():
      result[key] = [val[i] for i in sample_map]
  return result

We can see it works with Dataset.map() without us needing to remove the old columns:

In [69]:
tokenized_dataset = drug_dataset.map(tokenize_and_split, batched=True)
tokenized_dataset

  0%|          | 0/139 [00:00<?, ?ba/s]

  0%|          | 0/47 [00:00<?, ?ba/s]

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 206707
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 68864
    })
})

We get the same number of training features as before, but here we’ve kept all the old fields. If you need them for some post-processing after applying your model, you might want to use this approach.

You’ve now seen how 🤗 Datasets can be used to preprocess a dataset in various ways. Although the processing functions of 🤗 Datasets will cover most of your model training needs, there may be times when you’ll need to switch to Pandas to access more powerful features, like DataFrame.groupby() or high-level APIs for visualization. Fortunately, 🤗 Datasets is designed to be interoperable with libraries such as Pandas, NumPy, PyTorch, TensorFlow, and JAX. Let’s take a look at how this works.

### From Datasets to DataFrames and back


To enable the conversion between various third-party libraries, 🤗 Datasets provides a Dataset.set_format() function. This function only changes the output format of the dataset, so you can easily switch to another format without affecting the underlying data format, which is Apache Arrow. The formatting is done in place. To demonstrate, let’s convert our dataset to Pandas:

In [70]:
drug_dataset.set_format("pandas")

Now when we access elements of the dataset we get a pandas.DataFrame instead of a dictionary:

In [72]:
drug_dataset["train"][:3]

   patient_id    drugName  ... usefulCount review_length
0       95260  Guanfacine  ...         192           141
1       92703      Lybrel  ...          17           134
2      138000  Ortho Evra  ...          10            89

[3 rows x 8 columns]

Let’s create a pandas.DataFrame for the whole training set by selecting all the elements of drug_dataset["train"]:

In [75]:
train_df = drug_dataset["train"][:]
train_df.head()

   patient_id                  drugName  ... usefulCount review_length
0       95260                Guanfacine  ...         192           141
1       92703                    Lybrel  ...          17           134
2      138000                Ortho Evra  ...          10            89
3       35696  Buprenorphine / naloxone  ...          37           124
4      155963                    Cialis  ...          43            68

[5 rows x 8 columns]



```
Under the hood, Dataset.set_format() changes the return format for the dataset’s __getitem__() 
dunder method. This means that when we want to create a new object like train_df from a Dataset 
in the "pandas" format, we need to slice the whole dataset to obtain a pandas.DataFrame.
```

From here we can use all the Pandas functionality that we want. For example, we can do fancy chaining to compute the class distribution among the condition entries:

In [76]:
frequencies = (
    train_df["condition"].value_counts()
    .to_frame()
    .reset_index()
    .rename(columns={"index": "condition", "condition": "frequency"})
)
frequencies

               condition  frequency
0          birth control      27654
1             depression       8023
2                   acne       5209
3                anxiety       4991
4                   pain       4744
..                   ...        ...
814    parkinsonian trem          1
815   rabies prophylaxis          1
816  cerebral spasticity          1
817        myelofibrosis          1
818          neutropenia          1

[819 rows x 2 columns]

And once we’re done with our Pandas analysis, we can always create a new Dataset object by using the Dataset.from_pandas() function as follows:

In [77]:
from datasets import Dataset

freq_dataset = Dataset.from_pandas(frequencies)
freq_dataset

Dataset({
    features: ['condition', 'frequency'],
    num_rows: 819
})

This wraps up our tour of the various preprocessing techniques available in 🤗 Datasets. To round out the section, let’s create a validation set to prepare the dataset for training a classifier on. Before doing so, we’ll reset the output format of drug_dataset from "pandas" to "arrow":

In [78]:
drug_dataset.reset_format()

###  Creating a validation set


Although we have a test set we could use for evaluation, it’s a good practice to leave the test set untouched and create a separate validation set during development. Once you are happy with the performance of your models on the validation set, you can do a final sanity check on the test set. This process helps mitigate the risk that you’ll overfit to the test set and deploy a model that fails on real-world data.


🤗 Datasets provides a Dataset.train_test_split() function that is based on the famous functionality from scikit-learn. Let’s use it to split our training set into train and validation splits (we set the seed argument for reproducibility):

In [79]:
drug_dataset_clean = drug_dataset["train"].train_test_split(train_size=0.8, seed=42)
drug_dataset_clean["validation"] = drug_dataset_clean.pop("test")
drug_dataset_clean["test"] = drug_dataset["test"]
drug_dataset_clean

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 110807
    })
    validation: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 27702
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 46107
    })
})

we’ve now prepared a dataset that’s ready for training some models on!

###  Saving a dataset

Although 🤗 Datasets will cache every downloaded dataset and the operations performed on it, there are times when you’ll want to save a dataset to disk (e.g., in case the cache gets deleted).

🤗 Datasets provides three main functions to save your dataset in different formats:

* Arrow: Dataset.save_to_disk()
* CSV: Dataset.to_csv()
* JSON: Dataset.to_json()

For example, let’s save our cleaned dataset in the Arrow format:

In [80]:
drug_dataset_clean.save_to_disk("drug-reviews")

Flattening the indices:   0%|          | 0/111 [00:00<?, ?ba/s]

Flattening the indices:   0%|          | 0/28 [00:00<?, ?ba/s]

This will create a directory with the following structure:




```
drug-reviews/
├── dataset_dict.json
├── test
│   ├── dataset.arrow
│   ├── dataset_info.json
│   └── state.json
├── train
│   ├── dataset.arrow
│   ├── dataset_info.json
│   ├── indices.arrow
│   └── state.json
└── validation
    ├── dataset.arrow
    ├── dataset_info.json
    ├── indices.arrow
    └── state.json
```

where we can see that each split is associated with its own dataset.arrow table, and some metadata in dataset_info.json and state.json. You can think of the Arrow format as a fancy table of columns and rows that is optimized for building high-performance applications that process and transport large datasets.


Once the dataset is saved, we can load it by using the load_from_disk() function as follows:

In [81]:
from datasets import load_from_disk

drug_dataset_reloaded = load_from_disk("drug-reviews")
drug_dataset_reloaded

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 110807
    })
    validation: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 27702
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 46107
    })
})

For the CSV and JSON formats, we have to store each split as a separate file. One way to do this is by iterating over the keys and values in the DatasetDict object:

In [82]:
for split, dataset in drug_dataset_clean.items():
    dataset.to_json(f"drug-reviews-{split}.jsonl")

Creating json from Arrow format:   0%|          | 0/12 [00:00<?, ?ba/s]

Creating json from Arrow format:   0%|          | 0/3 [00:00<?, ?ba/s]

Creating json from Arrow format:   0%|          | 0/5 [00:00<?, ?ba/s]

For the CSV and JSON formats, we have to store each split as a separate file. One way to do this is by iterating over the keys and values in the DatasetDict object:

In [83]:
for split, dataset in drug_dataset_clean.items():
    dataset.to_json(f"drug-reviews-{split}.jsonl")

Creating json from Arrow format:   0%|          | 0/12 [00:00<?, ?ba/s]

Creating json from Arrow format:   0%|          | 0/3 [00:00<?, ?ba/s]

Creating json from Arrow format:   0%|          | 0/5 [00:00<?, ?ba/s]

This saves each split in JSON Lines format, where each row in the dataset is stored as a single line of JSON. Here’s what the first example looks like:

In [84]:
!head -n 1 drug-reviews-train.jsonl

{"patient_id":82885,"drugName":"Paxil","condition":"panic disorde","review":"\"I started taking Paxil about 2 months ago and it have saved my life. However the first two weeks of taking it was hell. When you first start taking it, your serotonin dips slightly because the drug is trying to adjust to your system. I suffer from a panic disorder and my anxiety was so bad that i had several extreme panic attacks where I have had to call up an ambulance. This happened 3 or 4 times during these weeks and one happened whilst I was driving on the dual carriageway. However these weeks are worth it, i can't even remember how to have a panic attack and my self confidence is as high as it's ever been.\"","rating":8.0,"date":"May 11, 2016","usefulCount":35,"review_length":119}

We can then use the techniques from earlier to load the JSON files as follows:

In [85]:
data_files = {
    "train": "drug-reviews-train.jsonl",
    "validation": "drug-reviews-validation.jsonl",
    "test": "drug-reviews-test.jsonl",
}
drug_dataset_reloaded = load_dataset("json", data_files=data_files)

WARNING:datasets.builder:Using custom data configuration default-b96a3186a01ca519

Downloading and preparing dataset json/default to /root/.cache/huggingface/datasets/json/default-b96a3186a01ca519/0.0.0/a3e658c4731e59120d44081ac10bf85dc7e1388126b92338344ce9661907f253...

Downloading data files:   0%|          | 0/3 [00:00<?, ?it/s]

Extracting data files:   0%|          | 0/3 [00:00<?, ?it/s]

0 tables [00:00, ? tables/s]

0 tables [00:00, ? tables/s]

0 tables [00:00, ? tables/s]

Dataset json downloaded and prepared to /root/.cache/huggingface/datasets/json/default-b96a3186a01ca519/0.0.0/a3e658c4731e59120d44081ac10bf85dc7e1388126b92338344ce9661907f253. Subsequent calls will reuse this data.

  0%|          | 0/3 [00:00<?, ?it/s]

And that’s it for our excursion into data wrangling with 🤗 Datasets! Now that we have a cleaned dataset for training a model on.

##  Big data? 🤗 Datasets to the rescue!